// admin/resources/js/Components/pages/main/reviews/Item.vue
<template>
    <div :class="classes.container">
        <div :class="['mb-2']">
            <span :class="classes.author">{{ review.name }}</span>
        </div>
        <p :class="[classes.message, 'm-0']">{{ review.text }}</p>

        <div :class="['mt-2', 'text-right']">
            <span :class="classes.date">01.01.2022</span>
        </div>
    </div>
</template>

<script>
import Styles from "@/Components/pages/main/reviews/Item.module.css";

export default {
    components: {},

    props: {
        review: Object,
    },

    data() {
        return {
            Styles,
        }
    },

    computed: {
        classes() {
            return {
                header: Styles.header,
                author: Styles.author,
                message: Styles.message,
                container: Styles.container,
                date: Styles.date,
            }
        },
    },
}
</script>

// client/components/pages/main/reviews/Item.tsx
import * as React from "react";
import cn from "classnames";
import Styles from "@components/pages/main/reviews/Item.module.scss";

interface IProps {
  review: Record<any, any>;
  className: any;
}

export const Item: React.FC<IProps> = function (props) {
  const { review, className } = props;

  return (
    <div className={cn([Styles.container, className])}>
      <div className={cn(["mb-2"])}>
        <span className={Styles.author}>{review.user.name}</span>
      </div>
      <p className={cn([Styles.message, "m-0"])}>{review.text}</p>

      <div className={cn(["mt-2", "text-end"])}>
        <span className={Styles.date}>01.01.2022</span>
      </div>
    </div>
  );
};

export default Item;
